= Endorsement Assertion
:toc: macro
:toc-title:
:sectanchors:
:sectnums:

An endorsement is a way of indicating approval for specific actions made on content after it has had a link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_manifests++[C2PA Manifest] attached. (See xref:_generating_an_endorsement[xrefstyle=full].) The *endorsement assertion* is where an endorsement from the signer of an ingredient asset is stored. These endorsements are typically provided (out-of-band of this specification) by ingredient asset signers to actors those signers trust to perform the actions listed in the assertion. They are used by a validator when assessing whether the actions of the active manifest are “endorsed” or not. (See xref:_validation[xrefstyle=full].)

Version 1.0 *Draft 04 March 2024* · xref:_version_history[]

[#maintainers]
*Maintainers:*

* mailto:scouten@adobe.com[Eric Scouten] (https://adobe.com[Adobe])

include::partial$license.adoc[]
include::partial$contributing.adoc[]
include::partial$foreword.adoc[]
include::partial$toc.adoc[]

== Introduction

_This section is non-normative._

=== Scope

IMPORTANT: For purposes of the Community Specification License, the link:https://github.com/creator-assertions/endorsement-assertion/blob/main/scope.md[`scope.md` document] at the root of this project’s GitHub repository is the governing document of this specification’s scope.

=== Overview

Endorsements are a way of indicating approval of three possible actions (see xref:_permitted_actions[xrefstyle=full]) that could be applied to an asset in a link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_manifests++[C2PA Manifest] in which the asset is used as an ingredient.

For example, the signer of a link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_manifests++[C2PA Manifest] may want to endorse another party who wishes to transcode its asset. The signer creates an endorsement that identifies the transcoder, and conveys the endorsement to them (in some method that is out-of-band from this specification). When the transcoder creates their asset containing the ingredient, they include the endorsement as an *endorsement assertion,* which lets the manifest consumer know that the actions they performed have been endorsed.

Endorsements are made by signers, and describe the actor they are endorsing through the use of their signing credentials and a validity period. These endorsements are conveyed out-of-band from the endorser to the endorsee. When the endorsee is using an asset created by the endorser as an ingredient in their own asset, they shall include the endorsement in its link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_manifests++[C2PA Manifest].

Endorsements endorse the specific actions (described in xref:_permitted_actions[xrefstyle=full]) that may be taken by the endorsee, and are therefore valid for asset manifests that use only the specified actions. Actions are only endorsed by the signer of that action’s referenced ingredient; they cannot be endorsed across more than multiple link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_manifests++[C2PA Manifests] in the asset’s provenance.

== Normative references

* https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html[C2PA technical specification, version 2.0]
* https://tools.ietf.org/html/rfc5280[Internet X.509 public key infrastructure certificate] (RFC 5280)

== Generating an endorsement

=== Endorsement storage

If the active manifest signer possesses an endorsement that it wishes to use to endorse an action performed by an actor, it can choose to embed the endorsement in the manifest it is generating. An endorsement is added as an *endorsement assertion* in the active manifest’s assertion store.

Before generating an *endorsement action,* the claim generator MUST ensure that:

* exactly one link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_actions++[`c2pa.actions` assertion] exists in the manifest,
* only the actions listed under xref:_permitted_actions[xrefstyle=full] are present in the actions assertion,
* exactly one link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_ingredient++[ingredient assertion] is present in the assertion store, and,
* that ingredient is the one referenced by the actions assertion’s `parameters.ingredient` field.

The *endorsement assertion* MUST have a label of `cawg.endorsement` and there SHALL be at most one *endorsement assertion* per manifest. The assertion contents MUST be a `COSE_Sign1_Tagged` structure that is created as defined in xref:_cose_payload_details[xrefstyle=full].

=== Permitted actions

The link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_actions++[`c2pa.actions` assertion] in a C2PA Manifest containing an *endorsement assertion* MAY contain any of the following action codes:

* `c2pa.published`
* `c2pa.transcoded`
* `c2pa.repackaged`

The actions assertion MUST NOT contain any other action codes.

=== COSE payload details

Endorsements are COSE objects (see link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_digital_signatures++[Section 13.2, “Digital Signatures,” of the C2PA 2.0 Technical Specification]), where the COSE payload is an “endorsement target” data structure encoded as CBOR, as shown below. The `endorseeCredential` field is an object with a single field, labelled according to the type of credential used to sign the endorsement. The label of this field indicates to validators the type of the credential present, so that they know how to decode, parse and validate the credential correctly. The following table details the format of each of the currently specified credential types:

==== Endorsement credential types

[col="2,1,4,4"]
|===
|Credential name |CBOR label |Value type |Compares To

|Reserved
|0
|
|

|X.509 SubjectPublicKeyInfo
|1
|A https://datatracker.ietf.org/doc/html/rfc5280#section-4.1[DER-encoded ASN.1 SubjectPublicKeyInfo] structure (as a CBOR `bstr`), from the _endorsee’s_ X.509 certificate that will be used for signing the claims of assets that this endorsement is expected to be used with.
|The value of the credential shall be compared (bitwise identical) to the SubjectPublicKeyInfo structure of the certificate located in the `x5chain` or `33` (integer) COSE header of the active manifest Claim Signature. (See link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#x509_certificates++[Section 14.6, “X.509 Certificates,” of the C2PA 2.0 Technical Specification].)
|===

Endorsers SHALL place the credential of the signer they are endorsing and its type in the `endorseeCredential`. To limit the length of time that an endorser is lending their endorsement to another signer, the `notValidBefore` and `notValidAfter` fields contain ISO 8601 date times.

The schema for the endorsement target type is defined by the `endorsement-target-map` rule in the following https://datatracker.ietf.org/doc/html/rfc8610[CDDL Definition]:

[source,cddl]
----
include::partial$schemas/cddl/endorsement-target.cddl[]
----

An example endorsement target is shown below:

[source,json]
----
include::partial$schemas/cddl/examples/endorsement-target.cbordiag[]
----

To sign an endorsement, follow the procedure specified in link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_digital_signatures++[Section 13.2, “Digital Signatures,” of the C2PA 2.0 Technical Specification], using the serialised CBOR `endorsement-target` object as the contents of the payload field. A signer SHALL NOT include a `x5chain` header and value, as endorsements are validated in the context of their use as an ingredient, and therefore use the signing credential of that ingredient manifest. (See xref:_validation[xrefstyle=full].) The serialized `COSE_Sign1_Tagged` structure resulting from the digital signature procedure is the endorsement that may be conveyed to the signer identified in the `endorsement-target`, but the process for conveying it is out of scope of this specification.

== Validation

Endorsement validation SHALL only be attempted if the active manifest first meets a number of conditions:

* There is exactly one link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_actions++[actions assertion] present in the assertion store.
* There is exactly one link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_ingredient++[ingredient assertion].

Retrieve the *endorsement assertion* in the active manifest, as described in xref:_endorsement_storage[xrefstyle=full]. In order to provide resilience in the case of a claim generator unexpectedly adding multiple *endorsement assertions* to an assertion store, a validator MAY iterate through the validation process below with each endorsement, stopping the iteration immediately if an endorsement validates successfully.

For each `action` object in the link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_actions++[actions assertion] :

. Check that the `action` field is set to `c2pa.published`, `c2pa.transcoded` or `c2pa.repackaged`. If any other action is present, fail the endorsement process for this manifest and do not proceed with further validation.
. Check the `ingredient` field that is a member of the `parameters` object for the presence of a JUMBF URI. If the JUMBF URI is not present, or cannot be resolved to the related ingredient assertion, skip endorsement for this action.
. Follow the JUMBF URI link in the `ingredient` field to the ingredient assertion. Check that the URI link resolves to an assertion in the active manifest. If it does not, skip endorsement for this action. Check that the `relationship` field is `parentOf`. If it is not, skip endorsement for this action.
. Check the `c2pa_manifest` field in the ingredient assertion for the presence of a hashed URI. If the hashed URI is not present, or cannot be resolved to a manifest, skip endorsement for this action.
. Follow the JUMBF URI link in the `c2pa_manifest` field to the ingredient’s manifest. Ensure that this _ingredient_ manifest has been validated according to link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_recursively_validating_integrity_of_ingredients++[Section 15.8, “Recursively validating integrity of ingredients,” of the C2PA 2.0 Technical Specification], but do not skip the establishing of signer credential trust. If it does not validate, skip endorsement for this action.
. Validate the endorsement as described in link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_recursively_validating_integrity_of_ingredients++[Section 15.4, “Validate the signature,” of the C2PA Technical Specification], using the credential of the ingredient manifest signer. If a signing credential is present in the endorsement’s signature’s headers, it shall not be used for validation. If validation fails, skip this action.
. Validate the `endorsement-target` payload itself, following the steps below:
.. Compare the `endorseeCredential` to the credential of the active manifest signer, according to the table found in xref:_endorsement_credential_types[xrefstyle=full]. If the comparison fails, skip this endorsement.
.. If the active manifest is timestamped, then the _time-stamp_ must fall within the endorsement’s validity time range. If it does not, skip this endorsement.
.. If the active manifest is not timestamped, then the _time of validation_ must fall within the endorsement’s validity time range. If it does not, skip this endorsement.
.. If validation fails, skip this endorsement. If validation succeeds, mark that action as __endorsed__.

When endorsement validation has completed, for each actions assertion in the active manifest where all actions are marked as __endorsed__, the actions assertion itself shall be marked as __endorsed__ in the validation results returned by the validator.

include::partial$version-history.adoc[]
