endorsement-target-map = {
  "endorseeCredential" : public-credential,  ; A DER-encoded SubjectPublicKeyInfo containing the public key
  "notValidBefore": tdate, ; The date-time that this endorsement valid from, before this time it is not valid
  "notValidAfter": tdate ; The date-time that this endorsement expires and is no longer valid
  ? "metadata": $assertion-metadata-map, ; additional information about the assertion
}

public-credential = {
  $credential-type: any ; an extensible field allowing the specification of the credential payload
}

$credential-type /= 1 ; credentials with this type are a DER-encoded ASN.1 SubjectPublicKeyInfo structure, as a bstr (specification text for usage)